extends:
  - stylelint-config-html/astro
  - stylelint-config-standard
  - stylelint-config-recess-order
rules:
  selector-id-pattern: null
  selector-class-pattern: null
  custom-property-pattern: null
  keyframes-name-pattern: null